import os
from pathlib import Path

STATE_PATH = Path(__file__).resolve().parent / "app_state.txt"
CONFIG_DIR = Path.home() / ".stoptions_analyzer"
API_KEY_PATH = CONFIG_DIR / "api_key.txt"
DATA_DIR = Path(__file__).resolve().parent / "data"
API_BASE_URL = os.getenv("MASSIVE_BASE_URL", "https://api.polygon.io")
HORIZON_CONFIGS = [
    ("Day", 1, 10, "10m"),
    ("3 Day", 3, 30, "30m"),
    ("Week", 7, 60, "1h"),
    ("Month", 30, 120, "2h"),
    ("3M", 90, 360, "6h"),
    ("6M", 180, 720, "12h"),
    ("12M", 365, 1440, "1d"),
    ("3Y", 1095, 4320, "3d"),
    ("5Y", 1825, 7200, "5d"),
    ("10Y", 3650, 10080, "7d"),
]
ANALYSIS_OUTPUT_DIR = DATA_DIR / "analysis_outputs"
BACKTEST_CACHE_DIR = DATA_DIR / "backtest_cache"
BACKTEST_OUTPUT_DIR = DATA_DIR / "backtest_outputs"
DEFAULT_GENERAL_ANALYSIS_SETTINGS = {
    "analysis_type": "Cross-Sectional",
    "cross_sectional_strategy": "Momentum",
    "time_series_strategy": "Momentum",
    "lookback_days": 90,
    "skip_days": 5,
    "top_quantile": 0.2,
    "bottom_quantile": 0.2,
    "momentum_use_volatility_scaling": False,
    "momentum_use_residual": False,
    "momentum_use_multi_horizon": False,
    "time_series_use_volatility_scaling": False,
    "time_series_use_residual": False,
    "time_series_use_multi_horizon": False,
    "time_series_use_zscore": False,
    "time_series_winsorize_sigma": None,
    "output_dir": str(ANALYSIS_OUTPUT_DIR),
}

DEFAULT_BACKTEST_SETTINGS = {
    "strategy": "momentum",
    "strategy_name": "Time-Series Momentum",
    "lookback_days": "90",
    "skip_days": "5",
    "costs_bps": "5",
    "execution_model": "bps",
    "execution_spread_bps": "2",
    "execution_max_participation": "1.0",
    "execution_impact_bps": "5",
    "execution_latency_bars": "0",
    "execution_latency_ms": "0",
    "starting_capital": "100000",
    "bet_sizing_mode": "half_kelly",
    "custom_bet_pct": "10",
    "timeframe": "1m",
    "use_walk_forward": False,
    "wf_train_fraction": "0.70",
    "wf_validation_fraction": "0.15",
    "wf_test_fraction": "0.15",
    "wf_step_fraction": "0.15",
    "wf_cv_scheme": "walk_forward",
    "wf_purge_window_bars": "0",
    "wf_embargo_window_bars": "0",
    "wf_cpcv_n_groups": "6",
    "wf_cpcv_n_test_groups": "2",
    "wf_cv_seed": "42",
    "selected_entry_signals": "ts_momentum",
    "selected_exit_signals": "none",
    "xsmom_top_quantile": "0.2",
    "xsmom_bottom_quantile": "0.2",
    "xsmom_long_only": False,
    "xsmom_vol_lookback_days": "20",
    "portfolio_method": "equal_weight",
    "portfolio_vol_lookback_bars": "20",
    "portfolio_target_volatility": "0.10",
    "portfolio_max_symbol_weight": "0.25",
    "portfolio_max_sector_weight": "0.60",
    "portfolio_rebalance_frequency_bars": "1",
    "portfolio_clustering_linkage": "single",
    "portfolio_covariance_shrinkage": "0.15",
    "portfolio_max_gross_exposure": "1.0",
    "portfolio_min_net_exposure": "-1.0",
    "portfolio_max_net_exposure": "1.0",
    "portfolio_max_net_gamma": "",
    "portfolio_max_abs_vega_bucket": "",
    "portfolio_max_abs_delta_per_underlying": "",
    "start_date": "",
    "end_date": "",
    "notes": "",
    "governance_hypothesis_id": "",
    "governance_owner": "",
    "governance_dataset_snapshot_lock": "",
    "governance_acceptance_criteria": "",
    "governance_promotion_state": "research",
    "governance_approval_status": "pending",
    "governance_min_oos_periods": "3",
    "governance_min_stability_score": "0.55",
    "governance_max_turnover_total": "4.0",
    "governance_min_capacity_score": "0.5",
    "governance_max_signal_agreement_drift": "0.10",
    "governance_max_fill_slippage_drift_bps": "5.0",
    "governance_max_pnl_attribution_divergence": "0.15",
    "governance_expected_signal_agreement": "1.0",
    "governance_expected_fill_slippage_bps": "0.0",
    "governance_expected_pnl_attribution": "1.0",
    "governance_observed_signal_agreement": "1.0",
    "governance_observed_fill_slippage_bps": "0.0",
    "governance_observed_pnl_attribution": "1.0",
    "stress_enable_historical_replay_regimes": True,
    "stress_historical_window_fraction": "0.20",
    "stress_historical_replay_window_bars": "20",
    "stress_synthetic_jump_magnitude": "0.02",
    "stress_synthetic_jump_interval": "7",
    "stress_synthetic_vol_cluster_multiplier": "1.6",
    "stress_overlay_spread_multiplier": "2.5",
    "stress_overlay_liquidity_multiplier": "0.4",
    "ui_mode": "basic",
    "selected_preset": "custom",
    "selected_template": "",
    "backtest_data_root": str(BACKTEST_CACHE_DIR),
}

BACKTEST_STRATEGY_PRESETS = {
    "daily_trend": {
        "label": "Daily Trend",
        "settings": {
            "strategy": "momentum",
            "timeframe": "1d",
            "lookback_days": "120",
            "skip_days": "5",
            "selected_entry_signals": "ma_trend,breakout",
            "selected_exit_signals": "momentum_flip,max_hold",
            "portfolio_method": "equal_weight",
            "costs_bps": "2",
        },
    },
    "intraday_momentum": {
        "label": "Intraday Momentum",
        "settings": {
            "strategy": "momentum",
            "timeframe": "5m",
            "lookback_days": "80",
            "skip_days": "3",
            "selected_entry_signals": "ts_momentum,breakout",
            "selected_exit_signals": "trailing_stop,momentum_flip",
            "portfolio_method": "vol_target",
            "costs_bps": "8",
        },
    },
    "xsmom_baseline": {
        "label": "XSMOM Baseline",
        "settings": {
            "strategy": "xsmom",
            "timeframe": "1d",
            "lookback_days": "90",
            "skip_days": "5",
            "xsmom_top_quantile": "0.2",
            "xsmom_bottom_quantile": "0.2",
            "xsmom_long_only": False,
            "xsmom_vol_lookback_days": "20",
            "costs_bps": "5",
        },
    },
}

DEFAULT_MODEL_PARADIGM_CONFIG = {
    "paradigms": [
        {"name": "momentum", "enabled": True, "weight": 1.0},
        {"name": "mean_reversion", "enabled": True, "weight": 1.0},
        {"name": "volatility_carry", "enabled": True, "weight": 1.0},
        {"name": "term_structure_slope", "enabled": True, "weight": 1.0},
        {"name": "dispersion", "enabled": True, "weight": 1.0},
        {"name": "stat_arb_pair_spread", "enabled": True, "weight": 1.0},
        {"name": "factor_neutral_cross_sectional_rank", "enabled": True, "weight": 1.0},
        {"name": "macro_regime_conditioned", "enabled": True, "weight": 1.0},
        {"name": "event_driven", "enabled": True, "weight": 1.0},
        {"name": "options_flow_driven", "enabled": True, "weight": 1.0},
        {"name": "options_directional", "enabled": True, "weight": 1.0},
        {"name": "options_volatility", "enabled": True, "weight": 1.0},
        {"name": "microstructure_imbalance", "enabled": True, "weight": 1.0},
        {"name": "meta_label_classifier", "enabled": True, "weight": 1.0},
    ]
}
